### ISSUE TITLE
Error de configuración de eslint al ejecutar los tests.

### ISSUE THREAD

**Issue by archenemy** [mozdevs/js-for-gamedev#15]
Hola!

He descargado el paquete (start-here.zip) de la primera práctica y seguido las instrucciones en un entorno OSX El Capitán 10.11.6, con la salvedad de que tengo instalada la versión 7.6.0 de node en lugar de la 6 indicada en la sección sobre entorno de trabajo (proporcionada por homebrew y utilizada en otros scripts gulp locales)

`archenemy at fgm-mba in ~/Projects/gamedev/start-here
$ node -v
v7.6.0`

Al ejecutar 'npm test' inmediatamente después de 'npm install' obtengo el siguiente resultado.

```sh
archenemy at fgm-mba in ~/Projects/gamedev/start-here

$ npm test
pvli2017-rpg-battle@1.0.0 test /Users/archenemy/Projects/gamedev/start-here
node ./node_modules/gulp/bin/gulp.js test
[15:44:55] Using gulpfile ~/Projects/gamedev/start-here/gulpfile.js
[15:44:55] Starting 'lint'...
[15:44:55] Finished 'lint' after 59 ms
[15:44:55] Starting 'test'...
[15:44:55] Finished 'test' after 36 ms
/Users/archenemy/Projects/gamedev/start-here/node_modules/eslint/lib/config.js:170
            throw noConfigError;
            ^
Error: No ESLint configuration found.
    at getLocalConfig (/Users/archenemy/Projects/gamedev/start-
here/node_modules/eslint/lib/config.js:162:35)
    at Config.getConfig (/Users/archenemy/Projects/gamedev/start-here/node_modules/eslint/lib/config.js:260:26)
    at processText (/Users/archenemy/Projects/gamedev/start-here/node_modules/eslint/lib/cli-engine.js:224:33)
    at CLIEngine.executeOnText (/Users/archenemy/Projects/gamedev/start-here/node_modules/eslint/lib/cli-engine.js:754:26)
    at verify (/Users/archenemy/Projects/gamedev/start-here/node_modules/gulp-eslint/index.js:20:25)
    at Transform.util.transform [as _transform] (/Users/archenemy/Projects/gamedev/start-here/node_modules/gulp-eslint/index.js:70:17)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
npm ERR! Test failed.  See above for more details.
```

Espero que resulte útil y legible, no consigo formatear las trazas en condiciones.

**Comment by delapuente** [comment]
You should be able to download the linter config file inside the zip now.

**Comment by archenemy** [comment]
Thanks! It's working as expected now.

PS: Notes taken on how to format traces for the next issues ;). Thanks again.
